package com.nadiahassouni.fixup.models

class Wilayas {
    fun loadWilayas() : List<String>{
        return listOf(
            "Adrar" ,
            "Chlef" ,
            "Laghoua" ,
            "Bouaghi" ,
            "Batna",
            "Bejaia" ,
            "Biskara" ,
            "Bechar" ,
            "Blida" ,
            "Bouira" ,
            "Tamanrasset" ,
            "Tebessa",
            "Telemcen",
            "Tiaret",
            "Ouzou",
            "Alger",
            "Djelfa",
            "Jijel",
            "Setif",
            "Saida",
            "Skikda",
            "Abbes",
            "Annaba",
            "Geulma",
            "Constantine",
            "Medea",
            "Mostaganem",
            "Msila",
            "Mascara",
            "Ourgla",
            "Oran",
            "Bayadh",
            "Illizi",
            "Arreridj",
            "Boumerdes",
            "Taref",
            "Tindouf",
            "Tissemsilt",
            "Oued",
            "Khenchela",
            "Souk Ahras",
            "Tipaza",
            "Mila",
            "Ain Defla",
            "Naama",
            "Ain Temouchent",
            "Ghardaia",
            "Relizan",
            "Timimoun",
            "Mokhtar",
            "Djellal",
            "Beni Abbes",
            "In Salah",
            "Guezzam",
            "Touggourt",
            "Djanet",
            "El Mghair",
            "Meniaa"
            )
    }
}